### ISSUE TITLE
BCCF code coverage is measured incoherently when counting non-unique blocks

### ISSUE THREAD

**Issue by v-p-b** [joxeankoret/nightmare#23]
BCCF configuration allows to generate coverage metrics based on non-unique basic blocks. However, this setting only has effect when generating initial metrics, but not when fuzzing cycles are executed:

https://github.com/joxeankoret/nightmare/blob/master/fuzzers/bcf.py#L264
https://github.com/joxeankoret/nightmare/blob/master/fuzzers/bcf.py#L498

This means that practically no fuzzing round will ever be able to produce better coverage than the inital ones. 

The following commit fixes this with a trivial patch, but my git-fu isn't strong enough today to create a proper pull request:

https://github.com/v-p-b/nightmare/commit/daea9945ac8eea6a291b9e260b5a863a11d9ace8

**Comment by hacksysteam** [comment]
Is this commit already in BCCF Code Coverage?

**Comment by hacksysteam** [comment]
Ah! I see the changes. Cool. Thanks.

**Comment by joxeankoret** [comment]
Yup, they are.
