### ISSUE TITLE
Little bug in gdb_iface.py

### ISSUE THREAD

**Issue by nixerr** [joxeankoret/nightmare#33]
gdb_iface.py:

```
288         crash_data.add_data("disassembly", int(self.pc), self.disasm)
289         for dis in self.disasm_around:
290           if type(dis[0]) is int or dis[0].isdigit():
291             crash_data.add_data("disassembly", dis[0], dis[1])

```
"type(dis[0])" also can be 'long', so if is true, we get exception.

patch is:

type(dis[0]) in (int, long)

**Comment by radare** [comment]
You can create a pullreq by just pressing the pencil button in the github ui which takes less time than describing it like this and allows to do proper review and merge of changes

**Comment by nixerr** [comment]
did
sorry, i didn't know about that :)

**Comment by radare** [comment]
np :) just trying to make the world a better place

**Comment by joxeankoret** [comment]
Thanks you! Bug fixed.
