### ISSUE TITLE
Add call to pykd.killAllProcesses()

### ISSUE THREAD

**Issue by hacksysteam** [joxeankoret/nightmare#35]
On line https://github.com/joxeankoret/nightmare/blob/master/lib/interfaces/pykd_iface.py#L320

There is a call missing to kill the process after the exception has occurred.

This can be fixed by adding pykd.killAllProcesses() after L320

**Comment by joxeankoret** [comment]
Uhm... why is it required? Is it really required?

**Comment by hacksysteam** [comment]
@joxeankoret Yeah, what I noticed that once the crash occurs, the crashing program is suspended and new instead is started without killing the suspended program. But adding **`pykd.killAllProcesses()`** fixes the issue.

**Comment by hacksysteam** [comment]
@joxeankoret **`pykd.killAllProcesses()`** will kill the the crashing program as well as the child processes spawned by it.

**Comment by joxeankoret** [comment]
OK, committed https://github.com/joxeankoret/nightmare/commit/10fa37bed5c739f3057b7cabdba9164ca5b63d6f
