### ISSUE TITLE
Pykd Interface Bug - Unable to kill Process

### ISSUE THREAD

**Issue by hacksysteam** [joxeankoret/nightmare#37]
Hi @joxeankoret 

I kept the test VM running with **`generic_fuzzer.py`** and every morning I find that the application hangs and it's not killed by the **`Timer`** thread.

https://github.com/joxeankoret/nightmare/blob/master/lib/interfaces/pykd_iface.py#L226

What I feel that **`pykd.breakin()`** is not sufficient to **kill the process**. I have added **`pykd.killAllProcesses()`** and hoping that it fixes the issue.

Same thing with https://github.com/joxeankoret/nightmare/blob/master/lib/interfaces/pykd_iface.py#L239

I will update you with my observation.

Thanks.

**Comment by joxeankoret** [comment]
This is a bug in pykd, I'm afraid. I will talk to the pykd's author about this and other bugs. Thanks for reporting!

**Comment by hacksysteam** [comment]
@joxeankoret The test failed, the issue still persists after adding **`pykd.killAllProcesses()`**. However, I have added **`self.time.join()`** after this line https://github.com/joxeankoret/nightmare/blob/master/lib/interfaces/pykd_iface.py#L275

I have kept it for test, I'll update you again.

Thanks.

**Comment by ussrhero** [comment]
pykd.breakin() does not terminate a process. 'breakin' is intended to make a debug break in the running process(s).

**Comment by joxeankoret** [comment]
@hacksysteam The fuzzer generic_fuzzer.py when using pykd should only execute one process at a time. Indeed, in my own automations, I execute it in a loop pooling just one sample at a time. There are other debugging interfaces, like the GDB's one, that suffer from this problem.

@ussrhero After executing a number of times pykd.killAllProcesses() correctly, it simply freezes for no reason. It happened to me a lot of times with multi-process targets after many hours (is not something you can reproduce always so I suspect some kind of race condition). As so, I removed the code for killing processes and left exclusively the .breakin() call for reading stuff as when exiting from the Python script the debugged processes effectively die.
