### ISSUE TITLE
Wrap L222-L250 in try/except

### ISSUE THREAD

**Issue by hacksysteam** [joxeankoret/nightmare#38]
Hi @joxeankoret 

There was a case the fuzzer stopped working with error: **Error: [Errno 10054] An existing connection was forcibly closed by the remote host.**

I believe that this was cased by fuzzer trying to get the buffer from the queue and something wrong happened.

**Comment by hacksysteam** [comment]
We need additional validation to ensure that the connection is restored.

@joxeankoret is there any feature in nightmare to track node status? I mean to check if they are alive or dead.

**Comment by joxeankoret** [comment]
I think that the problem is other: generic_fuzzer.py with WinDbg (Pykd) backend is meant to be launched once. Have you tried launching the tool in a loop?

**Comment by hacksysteam** [comment]
@joxeankoret Actually, we do not need to set any loop the https://github.com/joxeankoret/nightmare/blob/master/fuzzers/generic_fuzzer.py#L221 already does that. I added try/except so that it does not crash if any issues occurs, rather it re-tries it.

**Comment by joxeankoret** [comment]
Yes, we need to put a loop because the pykd debugging interface may lock, for no reason, after hours.

**Comment by hacksysteam** [comment]
Yeah...
