### ISSUE TITLE
CreateProcess failed.

### ISSUE THREAD

**Issue by fuzzers** [joxeankoret/nightmare#39]
Please change 
        crash = self.iface.main(" ".join(cmd))
to 
        crash = self.iface.main(cmd)
in generic_fuzzer.py line 176.

This is causing CreateProcess failed when not using 'asan' as debugging interface.

Thanks!

**Comment by joxeankoret** [comment]
Arg... true. Let me fix it...

**Comment by joxeankoret** [comment]
Should be fixed with 90246faf1ecb95849075883a894d5f5e34f98494
