### ISSUE TITLE
How to fuzzing Antivirus on Windows?

### ISSUE THREAD

**Issue by sucof** [joxeankoret/nightmare#43]
Hi, I want to fuzzing antivirus on windows 7, have any tutorials inthere?

**Comment by joxeankoret** [comment]
Sorry, but "fuzzing antivirus on Windows" is neither a trivial question nor something that Nightmare tries to fix.

What I have done, however, is to find the Unix/Linux version of the AV you're targeting or, alternatively, an independent command line scanner for that AV and try to fuzz that. If we're talking about fuzzing the resident (the scanner service), that is totally non trivial and absolutely specific to every single AV.

**Comment by sucof** [comment]
thx, just for fuzzing scanner service
