### ISSUE TITLE
I want to use fuzzer in more than one system

### ISSUE THREAD

**Issue by AniruddhaDD** [joxeankoret/nightmare#44]
I didn't find any documentation related to how to configure fuzzer in distributed systems. I want to use nightmare fuzzer in more than one system(distributed system).

**Comment by joxeankoret** [comment]
Copy the source tree to your target destination(s), along with the configuration file for your fuzzer (i.e., with generic_fuzzer.py your generic.cfg), be sure that the client machine can connect to the beanstalk queue in the server (port 11300 by default), modify your $NIGHTMARE_DIR/runtime/config.py to point to your beanstalk's server hostname and port and, voilà!

**Comment by AniruddhaDD** [comment]
**@joxeankoret** Its working, Thank You!

**Comment by joxeankoret** [comment]
Glad to read that :)
